const wordList = [
    { word: "PYTHON", hint: "Un langage de programmation populaire. 🐍" },
    { word: "JAVA", hint: "Utilisé pour le développement web et mobile. ☕" },
    { word: "JAVASCRIPT", hint: "Langage essentiel pour le développement web interactif. 🌐" },
    { word: "CPLUSPLUS", hint: "Un langage puissant utilisé pour les jeux et les systèmes embarqués. 🎮" },
    { word: "SWIFT", hint: "Langage principal pour développer des applications iOS. 📱" },
    { word: "PHP", hint: "Utilisé pour créer des sites web dynamiques. 💻" },
    { word: "RUST",
     hint: "Connu pour sa sécurité et ses performances. ⚡" },
    { word: "RUBY", hint: "Apprécié pour sa simplicité et son élégance. 💎" },
    { word: "DART", hint: "Utilisé pour développer avec Flutter. 🎯" },
    { word: "KOTLIN", hint: "Le langage préféré pour les applications Android. 🤖" },
    { word: "VARIABLE", hint: "Stocke des valeurs dans un programme. 🔢" },
    { word: "FONCTION", hint: "Un bloc de code réutilisable. ⚙️" },
    { word: "TABLEAU", hint: "Une structure de données qui stocke plusieurs valeurs. 📊" },
    { word: "BOUCLE", hint: "Une instruction qui répète une action plusieurs fois. 🔄" },
    { word: "OBJET", hint: "Une instance d'une classe en POO. 🎭" },
    { word: "CLASSE", hint: "Un modèle pour créer des objets. 🏛️" },
    { word: "ALGORITHME", hint: "Une suite d’instructions pour résoudre un problème. 🤖" },
    { word: "CONDITION", hint: "Permet d’exécuter un code selon un critère. ✅❌" },
    { word: "MÉTHODE", hint: "Une fonction définie dans une classe. 🔍" },
    { word: "LIBRAIRIE", hint: "Un ensemble de fonctions réutilisables. 📚" },
    { word: "REACT", hint: "Une bibliothèque JavaScript pour les interfaces utilisateur. ⚛️" },
    { word: "ANGULAR", hint: "Un framework JavaScript développé par Google. 🔥" },
    { word: "VUE", hint: "Un framework JavaScript progressif. 🖼️" },
    { word: "NODEJS", hint: "Permet d'exécuter du JavaScript côté serveur. 🌍" },
    { word: "LARAVEL", hint: "Un framework PHP pour le développement web. 🚀" },
    { word: "FLASK", hint: "Un framework léger pour les applications Python. 🧪" },
    { word: "DJANGO", hint: "Un framework Python pour les applications web sécurisées. 🦎" },
    { word: "BOOTSTRAP", hint: "Une bibliothèque CSS pour créer des interfaces responsives. 🎨" },
    { word: "TAILWIND", hint: "Un framework CSS utilitaire. 🌬️" },
    { word: "SPRING", hint: "Un framework Java utilisé en entreprise. 🌱" }
];